#!/bin/bash
set -e -E -u -C -o pipefail

HOST=http://localhost:8080
ADMIN_ENDPOINT=$HOST/admin/repos
OUT=out/stresstest
NR_RPMS=40
NR_REPOS=10

create_repo() {
    curl -X PUT $ADMIN_ENDPOINT/$1 -i -s
}

echo "generate empty rpms"
SECONDS=0
rm -rf $OUT
mkdir -p $OUT
for I in $(seq $NR_RPMS); do
    (
        rm -f $OUT/foo-$I.spec
        sed "s/Version: .*/Version: $I/" res/foo.spec > $OUT/foo-$I.spec
        RPM_FILE=$(rpmbuild --define "_topdir $OUT/build" -bb $OUT/foo-$I.spec 2> /dev/null | sed -n "s/^Wrote: //;T;p")
        mv $RPM_FILE $OUT
        rm $OUT/foo-$I.spec
    ) &
done
wait
rm -rf $OUT/build
ls -1 $OUT/*.rpm | wc -l | grep $NR_RPMS
echo duration: $SECONDS seconds


echo "generate big rpms"
SECONDS=0
truncate -s 100MB $OUT/bar
echo duration: $SECONDS seconds


echo "create yum repos and yum.conf"
SECONDS=0
rm -rf repos/stressrepo*
for I in $(seq -w $NR_REPOS); do
    echo "create stressrepo$I"
    create_repo stressrepo$I | grep "201 CREATED" > /dev/null &
done
wait
ls -1d repos/stressrepo* | wc -l | grep $NR_REPOS

rm -f $OUT/yum.conf
exec 3>&1 >> $OUT/yum.conf

cat <<'EOF'
[main]
cachedir=out/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=out/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
distroverpkg=centos-release
EOF

for I in $(seq -w $NR_REPOS); do
    REPO=stressrepo$I
    echo
    echo "[$REPO]"
    echo "name=the $REPO"
    echo "baseurl=http://localhost:8080/repos/$REPO"
    echo "gpgcheck=0"
    echo "enabled=1"
done
exec 1>&3
echo duration: $SECONDS seconds


echo "stress yum repos"
SECONDS=0
(
    for I in $(seq -w $NR_REPOS); do
        (
            for RPM in $OUT/*.rpm; do
                curl -X POST $ADMIN_ENDPOINT/stressrepo$I -F rpm=@$RPM -i -s | grep "201 CONTENT CREATED" &
                sleep .01
            done
            wait
        ) &
        sleep .1
    done
    wait
    ls -1d repos/stressrepo* | wc -l | grep $NR_REPOS
) &
WORKER=$!
echo "worker: $WORKER"
(
    for I in $(seq 10); do
        echo "fetch repolist via yum, try $I"
        yum -c $OUT/yum.conf clean all
        yum -c $OUT/yum.conf repolist
    done
) &
OBSERVER=$!
echo "observer: $OBSERVER"
wait $WORKER
kill $OBSERVER || :
sleep 1
echo duration: $SECONDS seconds


echo "SUCCESS"
exit
