#!/bin/bash
set -e -E -u -C -o pipefail

HOST=${1:?no HOST given}
shift

cat <<'EOF'
[main]
cachedir=out/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=out/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
distroverpkg=centos-release
EOF

for I in $*; do
    REPO=$I
    echo
    echo "[$(basename $REPO)]"
    echo "name=the $REPO"
    echo "baseurl=$HOST/$REPO"
    echo "gpgcheck=0"
    echo "enabled=1"
done
