#!/bin/bash
set -u -e -E

mkdir -p target
git tag  | sort -V | head -n -5 > target/to_be_deleted
cat target/to_be_deleted

echo "These tags will be deleted! If you are unsure, hit Ctrl-C NOW!"
sleep 10

while read t; do
    git tag -d $t
    git push origin :refs/tags/$t
done < target/to_be_deleted

rm -f target/to_be_deleted
