#!/bin/bash
set -e -E -u

PYTHON_VERSION=${1:-}

VIRTUALENV_OPTS=${PYTHON_VERSION:+ -p /usr/bin/python$PYTHON_VERSION}
VENV=ve$PYTHON_VERSION

rm -rf $VENV
virtualenv $VENV $VIRTUALENV_OPTS

set +u
. $VENV/bin/activate
set -u

for LIB in $(find $PWD/src/main/python -mindepth 1 -maxdepth 1 -and -not -name "__pycache__"); do
    ln -sfv $LIB $VENV/lib/python*/site-packages/
done
for BIN in $(find $PWD/src/main/scripts -type f); do
    ln -sf $BIN $VENV/bin/
done

pip install --upgrade setuptools

pip install pybuilder
pyb install_dependencies

pyb

cat target/reports/coverage
