#!/bin/sh
set -e -E -o pipefail

SED=gsed

#git clean -fx
git rm *.rpm || :

cp ../../yumrepos-behind-nginx-on-centos7/tmp/*.rpm .

LATEST_YUMREPOS_RELEASE=$(curl -Is https://github.com/arnehilmann/yumrepos/releases/latest | $SED -n '/Location:/{s/.*: //;p}')
echo "latest yumrepos release: $LATEST_YUMREPOS_RELEASE"
DOWNLOAD_URL=$(echo $LATEST_YUMREPOS_RELEASE | $SED -n 's_v\([0-9\.]*\).*$_v\1/yumrepos-\1-py27.noarch.rpm_;s_/tag/_/download/_;p')
echo "download url: $DOWNLOAD_URL"

curl -OLs "$DOWNLOAD_URL"

echo "cleaning repodata"
rm -rf repodata/*
git checkout -- repodata/ || :
git rm -f repodata/* || :

echo "generating repodata"
docker run -v $PWD:/repo local/centos7-with-createrepo

git add *.rpm repodata/*
git status
