#!/usr/bin/env python
from yumrepos.app import create_application
from yumrepos.fs_backend import FsBackend

app = create_application(FsBackend('/tmp/repos'))
app.run(host="0.0.0.0", port=int("8080"))
