#!/bin/bash
set -e -E -u

cd /project
rpmbuild --rebuild --define "_topdir $PWD/build" yum-repos-*.src.rpm
BIN_RPM=$(echo build/RPMS/noarch/*.rpm)
mv $BIN_RPM .
rm -rf build
chown -R $(stat -c %u:%g .) .
rpm -qilp $(basename $BIN_RPM) --requires
